# All automations for Home Assistant exists here.

- id: snapshot_daily
  alias: 'Daily snapshot each monday through saturday of the week, kept 7 days'
  trigger:
    platform: time
    at: '00:01:00'
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
  action:
    service: auto_backup.backup_full
    data:
      name: ha_snapshot_daily_{{now().strftime('%Y%m%d_%H%M%S')}}
      keep_days: 7

- id: snapshot_weekly
  alias: 'Weekly snapshot each sunday, kept 57 days'
  trigger:
    platform: time
    at: '00:01:00'
  condition:
  - condition: time
    weekday:
      - sun
  action:
    service: auto_backup.backup_full
    data:
      name: ha_snapshot_weekly_{{now().strftime('%Y%m%d_%H%M%S')}}
      keep_days: 57