# All automations for Home Assistant exists here.

# Take snapshot each day of the week.
- id: snapshot_each_day
  alias: 'Snapshot each day of the week'
  trigger:
    platform: time
    at: '00:01:00'
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
  action:
    service: hassio.backup_full
    data_template:
      name: ha_snapshot_daily_{{now().strftime('%Y%m%d')}}

# Take weekly snapshot each sunday, approx. one hour after the daily.
- id: snapshot_weekly
  alias: 'Snapshot each sunday of the week'
  trigger:
    platform: time
    at: '00:01:00'
  condition:
  - condition: time
    weekday:
      - sun
  action:
    service: hassio.backup_full
    data_template:
      name: ha_snapshot_weekly_{{now().strftime('%Y%m%d')}}