# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Frontend
frontend:
  themes: !include_dir_merge_named themes

# Added 20230426 after HA halting twice in 2 weeks, set max_entries to 500
system_log:
  max_entries: 500

# https://github.com/jcwillox/hass-auto-backup/issues/9
logger:
  default: warn
  logs:
    supervisor.snapshots: info
    homeassistant.components.recorder: info
    homeassistant.components.sensor.sql: info
    custom_components.auto_backup: debug
# New
    homeassistant.core: info
# https://community.home-assistant.io/t/supervisor-log-entries-in-home-assistant-log/292522
    supervisor.hardware.monitor: info
    homeassistant.supervisor: info
    supervisor.hardware: info
    supervisor: info

# Recorder is enabled by default.
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
#auto_purge: true
  commit_interval: 30
  exclude:
    entities:
      # 20230312. We excluded these that do not have any purpose.
      - sensor.sn_3006917520_current_total
      - sensor.metering_total_yield_compensation

# Logbook is enabled by default.
logbook:

# History is enabled by default.
history:
  exclude:
    domains:
      # Updater: Is not required in history data.
      #- updater. Depreceated in 2022.3.3?
    entity_globs:
      # We do not include any of the test_-sensors.
      - binary_sensor.test_*
      - sensor.test_*

# We utilize InfluxDB as state-history database.
influxdb:
  api_version: 2
  ssl: false
  host: 192.168.2.30
  port: 8086
  organization: lite
  bucket: ha
  token: !secret history_db_token
  max_retries: 3
  exclude:
    domains:
      # Updater: Is not required in history data.
      #- updater. Depreceated in 2022.3.3?
    entity_globs:
      # We do not include any of the test_-sensors.
      - binary_sensor.test_*
      - sensor.test_*
      # We exclude specific SMA related sensors, as we down-sample already in HA, and that they otherwise drive increase in database size.
      - sensor.metering_current_l1
      - sensor.metering_current_l2
      - sensor.metering_current_l3
      - sensor.sma_metering_current_l1_min
      - sensor.sma_metering_current_l1_mean
      - sensor.sma_metering_current_l1_max
      - sensor.sma_metering_current_l2_min
      - sensor.sma_metering_current_l2_mean
      - sensor.sma_metering_current_l2_max
      - sensor.sma_metering_current_l3_min
      - sensor.sma_metering_current_l3_mean
      - sensor.sma_metering_current_l3_max
      - sensor.metering_power_absorbed
      - sensor.sma_metering_power_absorbed_min
      - sensor.sma_metering_power_absorbed_mean
      - sensor.sma_metering_power_absorbed_max
      - sensor.metering_active_power_draw_l1
      - sensor.metering_active_power_draw_l2
      - sensor.metering_active_power_draw_l3
      - sensor.sma_metering_active_power_draw_l1_min
      - sensor.sma_metering_active_power_draw_l1_mean
      - sensor.sma_metering_active_power_draw_l1_max
      - sensor.sma_metering_active_power_draw_l2_min
      - sensor.sma_metering_active_power_draw_l2_mean
      - sensor.sma_metering_active_power_draw_l2_max
      - sensor.sma_metering_active_power_draw_l3_min
      - sensor.sma_metering_active_power_draw_l3_mean
      - sensor.sma_metering_active_power_draw_l3_max
      - sensor.metering_frequency
      - sensor.sma_metering_frequency_min
      - sensor.sma_metering_frequency_mean
      - sensor.sma_metering_frequency_max
      # 20221011. Exluded since we down-sample these as well.
      - sensor.grid_power
      - sensor.sma_grid_power_min
      - sensor.sma_grid_power_mean
      - sensor.sma_grid_power_max
      - sensor.metering_power_supplied
      - sensor.sma_metering_power_supplied_min
      - sensor.sma_metering_power_supplied_mean
      - sensor.sma_metering_power_supplied_max
      # 20221226. Excluded since we down-sample these.
      - sensor.pv_current_a
      - sensor.sma_pv_current_a_min
      - sensor.sma_pv_current_a_mean
      - sensor.sma_pv_current_a_max
      - sensor.pv_current_b
      - sensor.sma_pv_current_b_min
      - sensor.sma_pv_current_b_mean
      - sensor.sma_pv_current_b_max
      - sensor.pv_power_a
      - sensor.sma_pv_power_a_min
      - sensor.sma_pv_power_a_mean
      - sensor.sma_pv_power_a_max
      - sensor.pv_power_b
      - sensor.sma_pv_power_b_min
      - sensor.sma_pv_power_b_mean
      - sensor.sma_pv_power_b_max
      # 20221226. Excluded since we do not need to capture these (takes approx 1% or more of events)
      - sensor.sn_3006917520_current_total
      # 20230127. Excluded since they update every 5:th second, and we take snapshot each our instead (takes roughly 39% of events each per month).
      - sensor.metering_total_absorbed
      - sensor.metering_total_absorbed_cost
      # 20230219. Excluded since we do not need to capture these history_stats events, as we capture last value each hour.
      - sensor.balboa_spa_heater_running_time_hour
      # 20230222 (22:15). Excluded since it is not required to be captured, and it generates alot of data each hour.
      #                   Can be completely removed from Influx as we calculate yield compensation our own way.
      - sensor.metering_total_yield_compensation
      # 20230222 (22:15). Excluded since they update often, , and we take snapshot each our instead.
      - sensor.pv_gen_meter
      - sensor.total_yield
      - sensor.metering_total_yield
      - sensor.daily_yield
      # 20230223 (09:20). Excluded since we do not need to capture these history_stats events, as we capture last value each hour.
      - sensor.balboa_spa_circulationpump_running_time_hour
      # 20230223 (19:40). Excluded since we take snapshot each hour.
      - sensor.metering_active_power_feed_l1
      - sensor.metering_active_power_feed_l2
      - sensor.metering_active_power_feed_l3
      - sensor.sma_metering_active_power_feed_l1_min
      - sensor.sma_metering_active_power_feed_l1_max
      - sensor.sma_metering_active_power_feed_l1_mean
      - sensor.sma_metering_active_power_feed_l2_min
      - sensor.sma_metering_active_power_feed_l2_max
      - sensor.sma_metering_active_power_feed_l2_mean
      - sensor.sma_metering_active_power_feed_l3_min
      - sensor.sma_metering_active_power_feed_l3_max
      - sensor.sma_metering_active_power_feed_l3_mean

notify:
  - name: email_notification
    platform: smtp
    server: !secret email_server
    port: 587
    timeout: 15
    sender: !secret email_email_from
    recipient: !secret email_email_to
    starttls: true
    username: !secret email_email_from
    password: !secret email_password

# Text to speech
tts:
  - platform: google_translate

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - '/config/logs'
  packages:
    home_assistant: !include packages/home_assistant.yaml
    backup: !include packages/backup.yaml
    database_table_sizes: !include packages/database_table_sizes.yaml
    domains_entities: !include packages/domains_entities.yaml
    github_push: !include packages/github_push.yaml
    grafana_github_push: !include packages/grafana_github_push.yaml
    server1: !include packages/server1.yaml
    server1_github_push: !include packages/server1_github_push.yaml
    weather: !include packages/weather.yaml
    sma: !include packages/sma.yaml
    tariff_electrical: !include packages/tariff_electrical.yaml
    balboa_spa: !include packages/balboa_spa.yaml
    charger: !include packages/charger.yaml

shell_command:
  # We run copy_backup as background process, since otherwise HA will terminate the process after 60 seconds.
  copy_backup: /config/scripts/copy_backup.sh pi@192.168.2.30 /srv/ha/backup &
  github_push: /config/scripts/github_push.sh "{{ value }}"
  grafana_github_push: /config/scripts/grafana_github_push.sh pi@192.168.2.30 192.168.2.30:3000 "{{ value }}"
  server1_github_push: /config/scripts/server1_github_push.sh pi@192.168.2.30 "{{ value }}"