# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://github.com/jcwillox/hass-auto-backup/issues/9
logger:
  default: warn
  logs:
    supervisor.snapshots: info
    homeassistant.components.recorder: info
    homeassistant.components.sensor.sql: info
    custom_components.auto_backup: debug

# Recorder is enabled by default.
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
  #auto_purge: true
  commit_interval: 30

# Logbook is enabled by default.
logbook:

# History is enabled by default.
history:
  exclude:
    domains:
      # Updater: Is not required in history data.
      #- updater. Depreceated in 2022.3.3?
    entity_globs:
      # We do not include any of the test_-sensors.
      - binary_sensor.test_*
      - sensor.test_*

# We utilize InfluxDB as state-history database.
influxdb:
  api_version: 2
  ssl: false
  host: 192.168.2.30
  port: 8086
  organization: lite
  bucket: ha
  token: !secret history_db_token
  max_retries: 3
  exclude:
    domains:
      # Updater: Is not required in history data.
      #- updater. Depreceated in 2022.3.3?
    entity_globs:
      # We do not include any of the test_-sensors.
      - binary_sensor.test_*
      - sensor.test_*
      # We exclude specific SMA related sensors, as we down-sample already in HA, and that they otherwise drive increase in database size.
      - sensor.metering_current_l1
      - sensor.metering_current_l2
      - sensor.metering_current_l3
      - sensor.sma_metering_current_l1_min
      - sensor.sma_metering_current_l1_mean
      - sensor.sma_metering_current_l1_max
      - sensor.sma_metering_current_l2_min
      - sensor.sma_metering_current_l2_mean
      - sensor.sma_metering_current_l2_max
      - sensor.sma_metering_current_l3_min
      - sensor.sma_metering_current_l3_mean
      - sensor.sma_metering_current_l3_max
      - sensor.metering_power_absorbed
      - sensor.sma_metering_power_absorbed_min
      - sensor.sma_metering_power_absorbed_mean
      - sensor.sma_metering_power_absorbed_max
      - sensor.metering_active_power_draw_l1
      - sensor.metering_active_power_draw_l2
      - sensor.metering_active_power_draw_l3
      - sensor.sma_metering_active_power_draw_l1_min
      - sensor.sma_metering_active_power_draw_l1_mean
      - sensor.sma_metering_active_power_draw_l1_max
      - sensor.sma_metering_active_power_draw_l2_min
      - sensor.sma_metering_active_power_draw_l2_mean
      - sensor.sma_metering_active_power_draw_l2_max
      - sensor.sma_metering_active_power_draw_l3_min
      - sensor.sma_metering_active_power_draw_l3_mean
      - sensor.sma_metering_active_power_draw_l3_max
      - sensor.metering_frequency
      - sensor.sma_metering_frequency_min
      - sensor.sma_metering_frequency_mean
      - sensor.sma_metering_frequency_max
      # 20221011. Exluded since we down-sample these as well.
      - sensor.grid_power
      - sensor.sma_grid_power_min
      - sensor.sma_grid_power_mean
      - sensor.sma_grid_power_max
      - sensor.metering_power_supplied
      - sensor.sma_metering_power_supplied_min
      - sensor.sma_metering_power_supplied_mean
      - sensor.sma_metering_power_supplied_max
      # 20221226. Excluded since we down-sample these.
      - sensor.pv_current_a
      - sensor.sma_pv_current_a_min
      - sensor.sma_pv_current_a_mean
      - sensor.sma_pv_current_a_max
      - sensor.pv_current_b
      - sensor.sma_pv_current_b_min
      - sensor.sma_pv_current_b_mean
      - sensor.sma_pv_current_b_max
      - sensor.pv_power_a
      - sensor.sma_pv_power_a_min
      - sensor.sma_pv_power_a_mean
      - sensor.sma_pv_power_a_max
      - sensor.pv_power_b
      - sensor.sma_pv_power_b_min
      - sensor.sma_pv_power_b_mean
      - sensor.sma_pv_power_b_max
      # 20221226. Excluded since we do not need to capture these (takes approx 1% or more of events)
      - sensor.sn_3006917520_current_total

# Text to speech
tts:
  - platform: google_translate

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - '/config/logs'
  packages:
    home_assistant: !include packages/home_assistant.yaml
    backup: !include packages/backup.yaml
    database_table_sizes: !include packages/database_table_sizes.yaml
    domains_entities: !include packages/domains_entities.yaml
    github_push: !include packages/github_push.yaml
    grafana_github_push: !include packages/grafana_github_push.yaml
    server1: !include packages/server1.yaml
    weather: !include packages/weather.yaml
    sma: !include packages/sma.yaml
    tariff_electrical: !include packages/tariff_electrical.yaml
    balboa_spa: !include packages/balboa_spa.yaml
    charger: !include packages/charger.yaml

shell_command:
  # We run copy_backup as background process, since otherwise HA will terminate the process after 60 seconds.
  copy_backup: /config/scripts/copy_backup.sh pi@192.168.2.30 /srv/ha/backup &
  github_push: /config/scripts/github_push.sh "{{ value }}"
  grafana_github_push: /config/scripts/grafana_github_push.sh pi@192.168.2.30 192.168.2.30:3000 "{{ value }}"