# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: warn

# Recorder is enabled by default.
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
  auto_purge: true
  commit_interval: 10

# Logbook is enabled by default.
logbook:

# History is enabled by default.
history:
  exclude:
    domains:
      # Updater: Is not required in history data.
      #- updater. Depreceated in 2022.3.3?
    entity_globs:
      # We do not include any of the test_-sensors.
      - binary_sensor.test_*
      - sensor.test_*

# We utilize InfluxDB as state-history database.
influxdb:
  api_version: 2
  ssl: false
  host: 192.168.2.30
  port: 8086
  organization: lite
  bucket: ha
  token: !secret history_db_token
  max_retries: 3
  exclude:
    domains:
      # Updater: Is not required in history data.
      #- updater. Depreceated in 2022.3.3?
    entity_globs:
      # We do not include any of the test_-sensors.
      - binary_sensor.test_*
      - sensor.test_*
      # We exclude specific SMA related sensors, as we down-sample already in HA, and that they otherwise drive increase in database size.
      - sensor.metering_current_l1
      - sensor.metering_current_l2
      - sensor.metering_current_l3
      - sensor.sma_metering_current_l1_min
      - sensor.sma_metering_current_l1_mean
      - sensor.sma_metering_current_l1_max
      - sensor.sma_metering_current_l2_min
      - sensor.sma_metering_current_l2_mean
      - sensor.sma_metering_current_l2_max
      - sensor.sma_metering_current_l3_min
      - sensor.sma_metering_current_l3_mean
      - sensor.sma_metering_current_l3_max
      - sensor.metering_power_absorbed
      - sensor.sma_metering_power_absorbed_min
      - sensor.sma_metering_power_absorbed_mean
      - sensor.sma_metering_power_absorbed_max
      - sensor.metering_active_power_draw_l1
      - sensor.metering_active_power_draw_l2
      - sensor.metering_active_power_draw_l3
      - sensor.sma_metering_active_power_draw_l1_min
      - sensor.sma_metering_active_power_draw_l1_mean
      - sensor.sma_metering_active_power_draw_l1_max
      - sensor.sma_metering_active_power_draw_l2_min
      - sensor.sma_metering_active_power_draw_l2_mean
      - sensor.sma_metering_active_power_draw_l2_max
      - sensor.sma_metering_active_power_draw_l3_min
      - sensor.sma_metering_active_power_draw_l3_mean
      - sensor.sma_metering_active_power_draw_l3_max
      - sensor.metering_frequency
      - sensor.sma_metering_frequency_min
      - sensor.sma_metering_frequency_mean
      - sensor.sma_metering_frequency_max

# Text to speech
tts:
  - platform: google_translate

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - '/config/logs'
  packages:
    home_assistant: !include packages/home_assistant.yaml
    database_table_sizes: !include packages/database_table_sizes.yaml
    domains_entities: !include packages/domains_entities.yaml
    github_push: !include packages/github_push.yaml
    server1: !include packages/server1.yaml
    weather: !include packages/weather.yaml
    sma: !include packages/sma.yaml
    tariff_electrical: !include packages/tariff_electrical.yaml
    balboa_spa: !include packages/balboa_spa.yaml

shell_command:
  github_push: /config/scripts/github_push.sh "{{ value }}"
  test_command: /config/scripts/remote_stats.sh pi@192.168.2.30 cpu_temp value