# This file includes all the entitites for backup of home assistant.

# Updates made for Core updates and breaking changes:
# --------------------------------------------------------
# 20221108 - Clear to upgrade to 2022.6.7 from 2022.5.3: https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes Template filter/function defaults

automation:
  - id: snapshot_daily
    alias: "Daily snapshot each monday through saturday of the week, kept 7 days"
    trigger:
      platform: time
      at: "01:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
    action:
      service: auto_backup.backup_full
      data:
        name: ha_snapshot_daily_{{now().strftime('%Y%m%d_%H%M%S')}}
        keep_days: 7

  - id: snapshot_weekly
    alias: "Weekly snapshot each sunday, kept 57 days"
    trigger:
      platform: time
      at: "01:00:00"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      service: auto_backup.backup_full
      data:
        name: ha_snapshot_weekly_{{now().strftime('%Y%m%d_%H%M%S')}}
        keep_days: 57

  - id: copy_backup
    alias: "Copy backup files to server1 each night"
    trigger:
      platform: time
      at: "02:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      service: shell_command.copy_backup

  - id: copy_backup_manually
    alias: "Copy backup to server1"
    trigger:
      platform: state
      entity_id: input_button.copy_backup
    action:
      service: shell_command.copy_backup

input_button:
  copy_backup:
    name: Press to copy backup files to server1
    icon: mdi:cloud-upload
  copy_backup2:
    name: Press to copy backup files to server1 - v2
    icon: mdi:cloud-upload
# Removed 20241215 for 2024.12.3 since it has been converted to GUI-setup.
# The file platform for the sensor integration does not support platform setup. Please remove it from your config.
#sensor:
#    # Get the last line in the copy_backup-logfile
#  - platform: file
#    name: home_assistant_copy_backup_log
#    file_path: /config/logs/copy_backup.log
