# This file includes all the entitites for tracking Home Assistant.

# Updates made for Core updates and breaking changes:
# --------------------------------------------------------
# 20221108 - Clear to upgrade to 2022.6.7 from 2022.5.3: https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes Template filter/function defaults

sensor:
  # We want to keep track on when Home Assistant was restarted.
  # 20221113. Deprecated. Stops working in 2022.12.0, Configuration uptime using yaml has been removed. Available through Integrations.
#  - platform: uptime
#    name: home_assistant_restart
  # We wamt to keep track of basic OS/HW data, scan every 15 minute.
  - platform: systemmonitor
    scan_interval: 900
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_15m
      - type: processor_temperature
    # Get the last line in the file for backup from HA to server1.
  - platform: file
    name: home_assistant_backup_to_server1
    file_path: /config/logs/copy_backup.log

template:
  - sensor:
      # As we cannot use more reliable data, such as 'sar' and 'processor_use' is a snapshot.
      # We need to convert the load_15m dependent on cores.
      # On my system I have 4 cores (and no multi-threading).
      # Command 'nproc gives the number of cores.
      # Note that the load can be more than 100%.
      # https://scoutapm.com/blog/understanding-load-averages
      - name: Homeassistant cpu load 15m
        unique_id: homeassistant_cpu_load_15m
        icon: mdi:cpu-64-bit
        unit_of_measurement: '%'
        state_class: measurement
        state: "{{ (float(states('sensor.load_15m')) / 4) * 100 | round(2, default=0) }}"

automation:
  # https://community.home-assistant.io/t/recorder-purge-and-repack/110552
  - alias: Purge Database
    initial_state: True
    trigger:
      platform: time
      at: '03:00:00'
    action:
      service: recorder.purge
      data:
        keep_days: 30
        repack: true