# This file includes all the entitites for tracking Home Assistant.

# Updates made for Core updates and breaking changes:
# --------------------------------------------------------
# 20221108 - Clear to upgrade to 2022.6.7 from 2022.5.3: https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes Template filter/function defaults

sensor:
  # We want to keep track on when Home Assistant was restarted.
  # 20221113. Deprecated. Stops working in 2022.12.0, Configuration uptime using yaml has been removed. Available through Integrations.
#  - platform: uptime
#    name: home_assistant_restart
#  # We wamt to keep track of basic OS/HW data, scan every 15 minute.
# 20241126: Deprecated. In log 'The systemmonitor platform for the sensor integration does not support platform setup. Please remove it from your config.'
#           Can be remoeved as yaml.
#  - platform: systemmonitor
#    scan_interval: 900
#    resources:
#      - type: disk_use_percent
#        arg: /
#      - type: memory_use_percent
#      - type: swap_use_percent
#      - type: load_15m
#      - type: processor_temperature
#    # Get the last line in the file for backup from HA to server1.
  - platform: file
    name: home_assistant_backup_to_server1
    file_path: /config/logs/copy_backup.log

template:
  - sensor:
      # As we cannot use more reliable data, such as 'sar' and 'processor_use' is a snapshot.
      # We need to convert the load_15m dependent on cores.
      # On my system I have 4 cores (and no multi-threading).
      # Command 'nproc gives the number of cores.
      # Note that the load can be more than 100%.
      # https://scoutapm.com/blog/understanding-load-averages
      - name: Homeassistant cpu load 15m
        unique_id: homeassistant_cpu_load_15m
        icon: mdi:cpu-64-bit
        unit_of_measurement: '%'
        state_class: measurement
        state: "{{ (float(states('sensor.load_15m')) / 4) * 100 | round(2, default=0) }}"
      # 20230516:We add tracking of version for Core
      - name: Homeassistant Core installed_version
        unique_id: homeassistant_core_installed_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.home_assistant_core_update', 'installed_version') }}"
      # 20230516:We add tracking of version for Core
      - name: Homeassistant Core latest_version
        unique_id: homeassistant_core_latest_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.home_assistant_core_update', 'latest_version') }}"
        # 20230516:We add tracking of version for Supervisor
      - name: Homeassistant Supervisor installed_version
        unique_id: homeassistant_supervisor_installed_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.home_assistant_supervisor_update', 'installed_version') }}"
        # 20230516:We add tracking of version for Supervisor
      - name: Homeassistant Supervisor latest_version
        unique_id: homeassistant_supervisor_latest_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.home_assistant_supervisor_update', 'latest_version') }}"
        # 20230516:We add tracking of version for Operating System
      - name: Homeassistant OS installed_version
        unique_id: homeassistant_os_installed_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.home_assistant_operating_system_update', 'installed_version') }}"
        # 20230516:We add tracking of version for Operating System
      - name: Homeassistant OS latest_version
        unique_id: homeassistant_os_latest_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.home_assistant_operating_system_update', 'latest_version') }}"
        # 20230516:We add tracking of version for MariaDB
      - name: Homeassistant MariaDB installed_version
        unique_id: homeassistant_mariadb_installed_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.mariadb_update', 'installed_version') }}"
        # 20230516:We add tracking of version for MariaDB
      - name: Homeassistant MariaDB latest_version
        unique_id: homeassistant_mariadb_latest_version
        icon: mdi:home-assistant
        state: "{{ state_attr('update.mariadb_update', 'latest_version') }}"

automation:
  # Added 20230424, after twice halt of HA in two weeks.
  # We start with reboots every day.
  - alias: Restart HA regularly
    trigger:
      platform: time
      at: '23:02:00'
    condition:
      condition: time
      weekday:
        - sun
        - sat
        - fri
        - thu
        - wed
        - tue
        - mon
    action:
      - service: homeassistant.restart
  # Added 20230424, to get notification at restart.
  - alias: 'HA Startup Notification'
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: notify.email_notification
      data:
        title: "HA restarted"
        message: "HA has been restarted."
  # Added 20230424, to get notification at shutdown.
  - alias: 'HA shutdown notification'
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      service: notify.email_notification
      data:
        title: "HA shutdown"
        message: "HA has initiated shutdown."
  # Added 20230424, to get notification at errors or warning in log.
  - alias: 'HA log - Error or warning'
    trigger:
      - platform: event
        event_type: system_log_event
    action:
      service: notify.email_notification
      data:
        title: "HA log - Error or warning"
        message: >-
          Datetime: {{ trigger.timestamp | timestamp_custom('%Y%m%d %H:%M:%S') }}
          Level: {{ trigger.level }}
          Source: {{ trigger.source }}
          Name of component: {{ trigger.name }}
          Message: {{ trigger.message }}
  # https://community.home-assistant.io/t/recorder-purge-and-repack/110552
  - alias: Purge Database
    initial_state: True
    trigger:
      platform: time
      at: '03:00:00'
    action:
      service: recorder.purge
      data:
        keep_days: 30
        repack: true